server:
  port: 7799
cards:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_database
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  allow-get-accounts: true